import menues

#the input values for the test function
global input_values
input_values = ['1','BCR', 'Theodora Danciulescu', 'pass', '2', '1','BCR','Theodora Danciulescu','pass','Theodora Danciulescu2','2','1','Transilvania Bank', 
                'Theodora Danciulescu','pass','Theodora Danciulescu3','2', '2', 'BCR','Theodora Danciulescu', 'pass','1', 'Y' ,'3',
                'RO20BCR1000000000XX','1000', 'Y', '4', 'RO20BCR1000000000XX', '100', 'Y', '1','Y', '5', 'RO20BCR1000000000XX', 'RO20BCR1000000001XX',
                '500', 'Y', '4','RO20BCR1000000000XX','1000', 'Y', '3', 'RO20BCR2517139001XX', '10000', 'Y', '3', 'RO20BCR1000000000XX', '1000000000',  
                'N', 'Y', '6','RO20BCR1000000000XX','Y','6', 'RO20BCR1000000001XX', 'Y', '2', 'RO20BCR1000000001XX', 'N','N' ]

#test function using the override of input and print function
#------------------------------------------------------------
def test_app():
    output = []

    #override of the input and print function 
    def mock_input(s):
        output.append(s)
        return input_values.pop(0)
    menues.account.input = mock_input
    menues.input = mock_input
    menues.account.print = lambda s : output.append(s)
    menues.print = lambda s : output.append(s)
    menues.First_Menu()
    
    #compare the output generated by the program with the output correctly expected of the program
    assert output == ['Welcome to our application for banking!', 'What is the action you want to perform?\n', '1.Sign in\n2.Log in\n', 'Type in 1 or 2:', 
                      'Enter the bank where you want to be a user: ', 'Enter the ID: ', 'Enter the password: ', 'Account succesfully created!', 
                      'Do you want to suceed to the USER MENU(1) or go back to the FIRST MENU(2)?', 'Enter your option (1 or 2): ', 
                      'Welcome to our application for banking!', 'What is the action you want to perform?\n', '1.Sign in\n2.Log in\n', 'Type in 1 or 2:', 
                      'Enter the bank where you want to be a user: ', 'Enter the ID: ', 'Enter the password: ', 'ID already taken', 'Enter a different ID: ', 
                      'Account succesfully created!', 'Do you want to suceed to the USER MENU(1) or go back to the FIRST MENU(2)?', 
                      'Enter your option (1 or 2): ', 'Welcome to our application for banking!', 'What is the action you want to perform?\n', 
                      '1.Sign in\n2.Log in\n', 'Type in 1 or 2:', 'Enter the bank where you want to be a user: ', 'Enter the ID: ', 'Enter the password: ', 
                      'ID already taken', 'Enter a different ID: ', 'Account succesfully created!', 
                      'Do you want to suceed to the USER MENU(1) or go back to the FIRST MENU(2)?', 'Enter your option (1 or 2): ', 
                      'Welcome to our application for banking!', 'What is the action you want to perform?\n', '1.Sign in\n2.Log in\n', 
                      'Type in 1 or 2:', 'Enter the bank where you want to log in:', 'Enter the ID: ', 'Enter the password:', 
                      "You've logged in succesfully!\n", 'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n',
                         '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account', 
                         'Enter your option:', 'Account succesfully created!\nYour unique IBAN is: RO20BCR1000000000XX', 'Do you want to perform another transaction?',
                        'Enter Y/N:', 'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n', 
                        '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account', 
                        'Enter your option:', 'Enter the iban of the account you want to feed:', 'Enter the sum of money to insert:', 
                        'Transaction finished succesfully!', 'Do you want to perform another transaction?', 'Enter Y/N:', 
                        'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n', 
                        '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account', 
                        'Enter your option:', 'Enter the iban of the account you want to withdraw from:', 'Enter the sum of money to withdraw:', 
                        'Transaction finished succesfully!', 'Do you want to perform another transaction?', 'Enter Y/N:', 
                        'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n', 
                        '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account', 
                        'Enter your option:', 'Account succesfully created!\nYour unique IBAN is: RO20BCR1000000001XX', 'Do you want to perform another transaction?',
                       'Enter Y/N:', 'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n', 
                       '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account', 
                       'Enter your option:', 'Enter the iban of the account you want to transfer money from:', 'Enter the iban of the acount you want to tranfer money in:', 'Enter the sum of money you want to transfer:', 'Transaction finished succesfully!', 
                       'Do you want to perform another transaction?', 'Enter Y/N:', 'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n', '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account', 
                       'Enter your option:', 'Enter the iban of the account you want to withdraw from:', 'Enter the sum of money to withdraw:', 'Insufficient funds! TRANSACTION ABORTED! \n', 'Do you want to perform another transaction?', 
                       'Enter Y/N:', 'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n', 
                       '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account',
                      'Enter your option:', 'Enter the iban of the account you want to feed:', 'Enter the sum of money to insert:', 
                      'Transaction associated with a nonexisting account\n', 'Do you want to perform another transaction?', 'Enter Y/N:',
                     'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n', 
                     '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account', 
                     'Enter your option:', 'Enter the iban of the account you want to feed:', 'Enter the sum of money to insert:',
                    'The maximum sum of this account was reached! You cannot insert this sum of money! \n You can only add 9999600\n', 
                    'Agree to only add this much?', 'Enter Y/N: ', 'Transaction aborted', 'Do you want to perform another transaction?',
                   'Enter Y/N:', 'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n', 
                   '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account', 
                   'Enter your option:', 'Enter the iban of the account:', '======================= ACCOUNT REPORT =============================\n',
                  '----------------------- created on ' + menues.account.start_times['RO20BCR1000000000XX'] + ' untill ' + menues.account.end_times['RO20BCR1000000000XX'] +'---------------------------\n', 'Bank:BCR',
                 'IBAN code: RO20BCR1000000000XX\n', 'Account Holder ID:Theodora Danciulescu\n', 'Account currency:RON\n', 'Final balance: 400',
                'Record of all transaction:\n', 'The user inserted the sum of 1000 RON in the account on ' + menues.account.transaction_times[0] +'\n', 
                'The user extracted the sum of 100 RON from the account on ' + menues.account.transaction_times[1] +'\n', 
                'The user extracted the sum of 500 RON from the account on ' + menues.account.transaction_times[2] +'\n', 
                'Do you want to perform another transaction?', 'Enter Y/N:', 
                'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n',
               '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account',
              'Enter your option:', 'Enter the iban of the account:', '======================= ACCOUNT REPORT =============================\n',
             '----------------------- created on ' + menues.account.start_times['RO20BCR1000000001XX'] + ' untill ' + menues.account.end_times['RO20BCR1000000001XX'] +'---------------------------\n', 
             'Bank:BCR', 'IBAN code: RO20BCR1000000001XX\n', 'Account Holder ID:Theodora Danciulescu\n', 'Account currency:RON\n',
            'Final balance: 500', 'Record of all transaction:\n', 'The user inserted the sum of 500 RON in the account on ' + menues.account.transaction_times[3] +'\n',
           'Do you want to perform another transaction?', 'Enter Y/N:', 'HELLO! WELCOME TO YOUR USER MENU!\n\n What kind of transaction would you like to perform?\n', 
           '1.Open a new account\n2.Close an existing account\n3.Insert money in an existing account\n4.Withdraw money from an existing account\n5.Transfer money between 2 existing accounts\n6.Display a report of an existing account', 
           'Enter your option:', 'Enter the iban of the account to be closed:', 'Account succesfully closed!', 
           'Do you want to perform another transaction?', 'Enter Y/N:', 'Do you want to get back to the first menu?',
          'Enter Y/N:', 'Thank you for choosing us for your transactions!\n \n             Have a good day!']
    print("Tests passed succesfully!\n")
